Repository AY2324S2-CS2113-T15-2/tp, pull requests merged in 2024-04, with the labels that each got.

#57 Fix bug: Maintain program continuity post-insight popup closure
  src/main/java/budgetbuddy/insights/Insight.java
Labels: type.Bug

#58 Save account data
  .gitignore
  src/main/java/budgetbuddy/BudgetBuddy.java
  src/main/java/budgetbuddy/account/AccountManager.java
  src/main/java/budgetbuddy/storage/DataStorage.java
  src/main/java/budgetbuddy/transaction/TransactionList.java
  src/main/java/budgetbuddy/transaction/type/Expense.java
  src/main/java/budgetbuddy/transaction/type/Income.java
  src/test/java/budgetbuddy/storage/DataStorageTest.java
Labels: type.Task

#63 Fix add-acc command to print correct added account
  src/main/java/budgetbuddy/account/AccountManager.java
Labels: type.Bug, priority.High

#67 Fix delete acc to delete transactions related to account as well
  src/main/java/budgetbuddy/BudgetBuddy.java
  src/main/java/budgetbuddy/account/AccountManager.java
  src/main/java/budgetbuddy/transaction/TransactionList.java
  src/main/java/budgetbuddy/ui/UserInterface.java
Labels: type.Bug

#71 69 delete account one present
  src/main/java/budgetbuddy/account/AccountManager.java
  src/main/java/budgetbuddy/ui/UserInterface.java
Labels: type.Bug

#134 Update DG list feature
  docs/DeveloperGuide.md
  docs/uml/processList.puml
  docs/uml/uml-images/processList.png
Labels: type.Bug

#140 Fix list command
  src/main/java/budgetbuddy/BudgetBuddy.java
Labels: type.Bug

#145 Add exeption handling to readAccountFile method in DataStorage class
  src/main/java/budgetbuddy/storage/DataStorage.java
Labels: type.Bug

#146 Add newline read handling to DataStorage class
  src/main/java/budgetbuddy/storage/DataStorage.java
Labels: type.Bug

#147 Handle duplicate account number while reading account file
  src/main/java/budgetbuddy/storage/DataStorage.java
Labels: type.Bug

#148 Handle case where transaction refers to non-existing account
  src/main/java/budgetbuddy/BudgetBuddy.java
  src/main/java/budgetbuddy/account/AccountManager.java
  src/main/java/budgetbuddy/storage/DataStorage.java
  src/test/java/budgetbuddy/storage/DataStorageTest.java
Labels: type.Bug

#153 Fix clearing of account file if FileCorruptedException thrown
  src/main/java/budgetbuddy/storage/DataStorage.java
Labels: type.Bug

#167 Rename logger to LOGGER
  src/main/java/budgetbuddy/BudgetBuddy.java
  src/main/java/budgetbuddy/account/Account.java
  src/main/java/budgetbuddy/account/AccountManager.java
  src/main/java/budgetbuddy/storage/DataStorage.java
Labels: type.Bug
